version: '3.9'
services:
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - development
      - test
    volumes:
      - ./docker/postgres/scripts:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data:delegated
    ports:
      - "5433:5432"


volumes:
  postgres-data:

networks:
  development:
  test: